# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('faq_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Вопросы/ответы',
                'verbose_name': 'Вопрос/ответ',
                'db_table': 'faq',
            },
        ),
    ]
