# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('home_text', models.TextField(verbose_name='Текст статьи')),
                ('home_date', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
