# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='home_date',
        ),
    ]
