# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('about_text', models.TextField(verbose_name='Текст')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
                'db_table': 'about',
            },
        ),
    ]
