# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 22:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'db_table': 'shortabout',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='shortabout',
            name='short_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.About'),
        ),
    ]
